"""jwt

Revision ID: 8673b62a11e7
Revises: 6c56163bc0a5
Create Date: 2024-07-16 11:05:49.166231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8673b62a11e7'
down_revision: Union[str, None] = '6c56163bc0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt',
    sa.Column('access_key', sa.UUID(), nullable=False),
    sa.Column('refresh_key', sa.UUID(), nullable=False),
    sa.Column('refresh_token_exp_at', sa.DateTime(), nullable=False),
    sa.Column('access_token_exp_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_access_key'), 'jwt', ['access_key'], unique=True)
    op.create_index(op.f('ix_jwt_id'), 'jwt', ['id'], unique=False)
    op.create_index(op.f('ix_jwt_refresh_key'), 'jwt', ['refresh_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jwt_refresh_key'), table_name='jwt')
    op.drop_index(op.f('ix_jwt_id'), table_name='jwt')
    op.drop_index(op.f('ix_jwt_access_key'), table_name='jwt')
    op.drop_table('jwt')
    # ### end Alembic commands ###
