services:
  postgres:
    image: postgres:17.6-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    
volumes:
  postgres_data: