services:
  redis:
    image: redis/redis-stack:latest
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  mongodb:
    container_name: "mongodb"
    image: mongo:7.0.16 
    restart: always
    ports:
      - "27017:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db


  app:
    build:
      context: .
      dockerfile: dockerfile
    image: chat_system
    container_name: chat_service
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
    command:
      - /bin/bash
      - -c
      - |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    depends_on:
      - redis

volumes:
  mongo_data:
  redis_data:
    